name: campusapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_database: ^11.3.10
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  provider: ^6.1.1
  cloud_firestore: ^5.6.12
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  http_parser: ^4.0.2
  fluttertoast: ^8.0.9
  geolocator: ^11.0.0
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.0.0
  google_navigation_flutter: ^0.6.4
  permission_handler: ^11.3.1
  flip_card: ^0.7.0
  image_picker: ^1.0.4
  share_plus: ^10.0.2
  app_links: ^6.3.2
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/camphub.png
    - assets/camphub1.png
    - assets/camphub2.png
    - assets/mock_events/mock_events.json
    - assets/mock_schedule/schedule.json
    - assets/mock_subjects/mock_subjects.json
    - assets/.env
    - assets/images/
    - assets/splash_icon.png
    - assets/profile_picture.png

flutter_native_splash:
  # Required: Background color
  color: "#113F67"
  
  # Required: Your splash image (should be 1152x1152px for best results)
  image: assets/splash_icon.png
  
  # Platform support
  android: true
  ios: true
  web: true
  
  # Fullscreen mode
  fullscreen: true
  
  # Image positioning
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  
  # Android 12+ specific configuration
  android_12:
    image: assets/splash_icon.png
    color: "#113F67"